language: node_js
addons:
  ssh_known_hosts: 159.65.112.191
node_js:
  - 10.6.0
install:
  - npm ci
cache:
  directories:
    - node_modules
script:
  - npm test
before_deploy:
  - openssl aes-256-cbc -K $encrypted_fd0b00996591_key -iv $encrypted_fd0b00996591_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: ssh root@159.65.112.191 "cd app && ./deploy_node"
  on:
    branch: master
